---
profile::webserver::apache::vhosts:
  dpapp_ssl:
    ssl_ca:               "/etc/pki/tls/certs/DigiCertCA.crt"
    ssl_cert:             "/etc/pki/tls/certs/access_iaas_uio_no.crt"
    ssl_key:              "/etc/pki/tls/private/access_iaas_uio_no.key"
