---
profile::application::access::package_url: 'http://folk.uib.no/st02221/yum/himlar-dp-prep-1.0-1.el7.x86_64.rpm'

profile::webserver::apache::vhosts:
  dpapp:
    vhost_name:         "access.%{domain}"
    servername:         "access.%{domain}"
    port:               '80'
    manage_docroot:     false
    docroot:            '/var/www/html'
    redirect_dest:      "https://access.%{domain}/"
  dpapp_ssl:
    vhost_name:         "access.%{domain}"
    servername:         "access.%{domain}"
    port:               '443'
    manage_docroot:     false
    docroot:            '/var/www/html'
    wsgi_application_group:  '%%{}{GLOBAL}'
    wsgi_pass_authorization: 'on'
    wsgi_daemon_process:     'dpapp'
    wsgi_daemon_process_options:
      threads:      '4'
      python-path:  "%{hiera('dpapp::installdir')}/lib/python2.7/site-packages"
    wsgi_script_aliases:
      '/':   "%{hiera('dpapp::installdir')}/pyramid.wsgi"
    directories:
      - path:             "%{hiera('dpapp::installdir')}"
        require:          'all granted'
        custom_fragment:  'WSGIProcessGroup dpapp'
    ssl:                  true
    ssl_ca:               "/etc/pki/tls/certs/DigiCertCA.crt"
    ssl_cert:             "/etc/pki/tls/certs/dashboard_iaas_uio_no.crt"
    ssl_key:              "/etc/pki/tls/private/dashboard_iaas_uio_no.key"
