---
profile::application::access::package_url: 'http://folk.uib.no/st02221/yum/himlar-dp-prep-1.0-1.el7.x86_64.rpm'

profile::webserver::apache::vhosts:
  dpapp_ssl:
    ssl_ca:               "/etc/pki/tls/certs/DigiCertCA.crt"
    ssl_cert:             "/etc/pki/tls/certs/access_iaas_uio_no.crt"
    ssl_key:              "/etc/pki/tls/private/access_iaas_uio_no.key"
