---
profile::base::common::extraswap_fileloc: '/var/lib/swap/swapfile'

profile::base::lvm::physical_volume:
  '/dev/sda4':
    ensure: present
    force:  true
  '/dev/sdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_instances':
    physical_volumes:
      - /dev/sdb
  'vg_ext':
    physical_volumes:
      - /dev/sda4
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_instances'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"
  'lv_swap2':
    volume_group: 'vg_ext'
    fs_type:      xfs
    size:         40G
    mountpath:    "/var/lib/swap"
