---
profile::network::services::manage_dhcp:  false
profile::network::services::manage_nat:   true
profile::base::common::manage_network:    true

openstack_extras::repo::redhat::redhat::purge_unmanaged: false

# Disable centos yum repo
profile::base::yumrepo::repo_hash:
  CentOS-Base:
    ensure: absent
  CentOS-Updates:
    ensure: absent
  CentOS-Extras:
    ensure: absent

# Himlar bootstrap
profile::bootstrap::himlar::manage_bootstrap_scripts: true
himlar_bootstrap::tftp_install:
  osl-controller-01:
    domain:           'iaas.uio.no'
    dhcp_interface:   'em3'
    dhcp_range_start: '172.16.32.200'
    dhcp_range_end:   '172.16.32.250'
    dhcp_gateway:     '172.16.32.12'
  'test02-controller-01':
    domain:           'iaas.uio.no'
    dhcp_interface:   'em3'
    dhcp_range_start: "172.28.32.200"
    dhcp_range_end:   "172.28.32.250"
    dhcp_gateway:     "172.28.32.10"

profile::application::git::settings:
  hostname: "osl"
