---
profile::base::common::manage_cron: true
profile::base::common::manage_lvm: true
profile::base::cron::crontabs:
  stats:
    hour:     '*'
    minute:   [14,29,44,59]
    command:  '/opt/himlarcli/bin/gen_stats.sh >/dev/null 2>&1'
  checks:
    hour:     '*'
    minute:   '*/5'
    command:  '/opt/himlarcli/bin/check_services.sh >/dev/null 2>&1'
  update_images:
    hour:     '7'
    minute:   '15'
    monthday: '1'
    weekday:  '*'
    command:  '/opt/himlarcli/bin/image_update.sh >/dev/null 2>&1'
  sync_owners:
    hour:     '*/5'
    minute:   '0'
    command:  '/opt/himlarcli/bin/sync_owners.sh >/dev/null 2>&1'
  check_expired_demo_instances_60d:
    hour:     '5'
    minute:   '0'
    weekday:  '*'
    command:  '/opt/himlarcli/demo.py expired -d 60 -t notify/demo-notify-expired-instances-30dleft.txt --region osl'
  check_expired_demo_instances_75d:
    hour:     '6'
    minute:   '0'
    weekday:  '*'
    command:  '/opt/himlarcli/demo.py expired -d 75 -t notify/demo-notify-expired-instances-15dleft.txt --region osl'
  check_expired_demo_instances_89d:
    hour:     '7'
    minute:   '0'
    weekday:  '*'
    command:  '/opt/himlarcli/demo.py expired -d 89 -t notify/demo-notify-expired-instances-1dleft.txt --region osl'
  delete_expired_demo_instances_90d:
    hour:     '18'
    minute:   '0'
    weekday:  '*'
    command: '/opt/himlarcli/demo.py delete_expired_instance -d 90 --region osl'

profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_opt':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_opt':
    volume_group: 'vg_opt'
    fs_type:      "xfs"
    mountpath:    "/opt/himlarcli"
