---
profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    em1:
      'team_port_config': '{ "prio" : 100 }'
    em2:
      'team_port_config': '{ "prio" : 100 }'

profile::storage::cephosd::crush_parent:      'arccache'
profile::storage::cephosd::crush_parent_type: 'pod'

profile::base::common::manage_lvm: false
profile::base::lvm::create_lvm:    false

profile::storage::cephpool::manage_ec_pools: false
profile::storage::cephosd::create_osds: false
profile::storage::cephosd::crush_move:  false

profile::base::lvm::physical_volume:
  '/dev/sdn':
    ensure: present
    force:  true
  '/dev/nvme0n1':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_cache':
    physical_volumes:
      - /dev/nvme0n1
profile::base::lvm::logical_volume:
  'lv_dbb':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbc':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbd':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbe':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbf':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbg':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbh':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbi':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbj':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbk':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbl':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbm':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbo':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbp':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbq':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G
  'lv_dbr':
    volume_group: 'vg_cache'
    createfs:     false
    size:         96G

profile::storage::cephosd::osds:
  '/dev/sdb':
    db_device:  'vg_cache/lv_dbb'
    wal_device: false
  '/dev/sdc':
    db_device:  'vg_cache/lv_dbc'
    wal_device: false
  '/dev/sdd':
    db_device:  'vg_cache/lv_dbd'
    wal_device: false
  '/dev/sde':
    db_device:  'vg_cache/lv_dbe'
    wal_device: false
  '/dev/sdf':
    db_device:  'vg_cache/lv_dbf'
    wal_device: false
  '/dev/sdg':
    db_device:  'vg_cache/lv_dbg'
    wal_device: false
  '/dev/sdh':
    db_device:  'vg_cache/lv_dbh'
    wal_device: false
  '/dev/sdi':
    db_device:  'vg_cache/lv_dbi'
    wal_device: false
  '/dev/sdj':
    db_device:  'vg_cache/lv_dbj'
    wal_device: false
  '/dev/sdk':
    db_device:  'vg_cache/lv_dbk'
    wal_device: false
  '/dev/sdl':
    db_device:  'vg_cache/lv_dbl'
    wal_device: false
  '/dev/sdm':
    db_device:  'vg_cache/lv_dbm'
    wal_device: false
  '/dev/sdo':
    db_device:  'vg_cache/lv_dbo'
    wal_device: false
  '/dev/sdp':
    db_device:  'vg_cache/lv_dbp'
    wal_device: false
  '/dev/sdq':
    db_device:  'vg_cache/lv_dbq'
    wal_device: false
  '/dev/sdr':
    db_device:  'vg_cache/lv_dbr'
    wal_device: false
