---
named_interfaces::config:
  mgmt:
    - eno3
  transport:
    - team1
  trp:
    - team1
  ceph:
    - team1.110

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    ens6f0:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    ens6f1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# Ensure that the m.2 boot device is the last device
profile::base::physical::load_ahci_last:         true
profile::base::physical::load_ahci_last_scsidrv: 'megaraid_sas'

# placeholder data - FIXME
profile::storage::cephpool::manage_ec_pools: false
profile::storage::cephosd::crush_move:       false

profile::base::lvm::volume_group:
  'vg_swap':
    physical_volumes:
      - /dev/sdq4
  'vg_nvme1':
    physical_volumes:
      - /dev/nvme0n1
profile::base::lvm::logical_volume:
  'lv_swap2':
    volume_group: 'vg_swap'
    fs_type:      xfs
    size:         30G
    mountpath:    "/var/lib/swap"
  'lv_dbh':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         32G
  'lv_dbi':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         32G
  'lv_dbj':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         32G
  'lv_dbk':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         32G
  'lv_dbl':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         32G
  'lv_dbm':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         32G
  'lv_dbn':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         32G
  'lv_nvmeosd':
    volume_group: 'vg_nvme1'
    createfs:     false
    size:         1200G
profile::base::lvm::physical_volume:
  '/dev/nvme0n1':
    ensure: present
    force:  true

profile::storage::cephosd::osds:
  '/dev/sda':
    wal_device: false
    db_device:  false
  '/dev/sdb':
    wal_device: false
    db_device:  false
  '/dev/sdc':
    wal_device: false
    db_device:  false
  '/dev/sdd':
    wal_device: false
    db_device:  false
  '/dev/sde':
    wal_device: false
    db_device:  false
  '/dev/sdf':
    wal_device: false
    db_device:  false
  '/dev/sdg':
    wal_device: false
    db_device:  false
  '/dev/sdh':
    wal_device: false
    db_device:  'vg_nvme1/lv_dbh'
  '/dev/sdi':
    wal_device: false
    db_device:  'vg_nvme1/lv_dbi'
  '/dev/sdj':
    wal_device: false
    db_device:  'vg_nvme1/lv_dbj'
  '/dev/sdk':
    wal_device: false
    db_device:  'vg_nvme1/lv_dbk'
  '/dev/sdl':
    wal_device: false
    db_device:  'vg_nvme1/lv_dbl'
  '/dev/sdm':
    wal_device: false
    db_device:  'vg_nvme1/lv_dbm'
  '/dev/sdn':
    wal_device: false
    db_device:  'vg_nvme1/lv_dbn'
  '/dev/sdo':
    wal_device: false
    db_device:  false
  '/dev/sdp':
    wal_device: false
    db_device:  false
  '/dev/lv_nvmeosd'
    wal_device: false
    db_device:  false
