---
profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    p6p1:
      'team_port_config': '{ "prio" : 100 }'
    p6p2:
      'team_port_config': '{ "prio" : 100 }'

#profile::storage::cephosd::crush_parent:      'dcache'
#profile::storage::cephosd::crush_parent_type: 'pod'

profile::base::common::manage_lvm: false
profile::base::lvm::create_lvm:    false

profile::storage::cephpool::manage_ec_pools: false
profile::storage::cephosd::create_osds: false
profile::storage::cephosd::crush_move:  false
