---
profile::base::common::packages:
  'nfs-utils': {}

profile::openstack::volume::type:
  rbd:
    visibility: "public"
    properties:
      - 'volume_backend_name=rbd-volumes'
  nfs:
    visibility: "private"
    properties:
      - 'volume_backend_name=atlas-storage'

# Use transport network for this (which has no DNS name)
profile::openstack::volume::backend::nfs:
  atlas-storage:
    nfs_servers: ["172.18.32.80:/opt/volumeshare"]

cinder::api::default_volume_type: 'rbd'

cinder::backends::enabled_backends:
  - rbd-volumes
  - atlas-storage

