---
include:
  default:
    - profile::application::foreman
    - profile::database::postgresql
    - profile::network::services
    - profile::webserver::apache

foreman_version: '1.12'

profile::application::foreman::manage_eyaml:    true
profile::application::foreman::manage_firewall: true
profile::application::foreman::manage_repo_dir: true

profile::network::services::manage_dns_records: true
profile::network::services::manage_dhcp_rsvs:   true

openstack_extras::repo::redhat::redhat::purge_unmanaged:  false

## Bind utils will be installed with foreman::dns
#profile::base::common::packages:
#  'bind-utils': { ensure: absent }

puppet::server:                        true
puppet::server_foreman_url:            "https://%{fqdn}"
puppet::dns_alt_names:                 ["puppet.%{domain}","puppetca.%{domain}","admin.%{domain}"]

profile::webserver::apache::manage_firewall:  false
profile::webserver::apache::vhosts:
  'repo':
    servername:     "repo.%{domain}"
    port:           80
    docroot:        '/opt/repo/public'
    docroot_owner:  'iaas'

dhcp::onie_inst_def_url:     "http://repo.%{domain}/cumuluslinux/onie-installer-powerpc"
dhcp::cumulus_provision_url: "http://repo.%{domain}/cumuluslinux/provision.sh"

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  foreman:
    ensure: present
  foreman-plugins:
    ensure: present
