---
include:
  default:
    - profile::storage::cephmds

profile::storage::cephmds::manage_firewall:  true

profile::base::common::packages:
  'redhat-lsb-core': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}

network::interfaces_hash:
  'eth0':
    netmask:   "%{hiera('netcfg_mgmt_netmask')}"
    gateway:   "%{hiera('netcfg_mgmt_gateway')}"
    mtu:       '1500'
    peerdns:   'yes'
    dns1:      "%{hiera('netcfg_dns_server1')}"
    dns2:      "%{hiera('netcfg_dns_server2')}"
    domain:    "%{hiera('netcfg_dns_search')}"
    defroute:  'yes'
  'eth1':
    netmask:   "%{hiera('netcfg_trp_netmask')}"
    defroute:  'no'
    mtu:       '1500'
