---
include:
  default:
    - profile::storage::cephmds

profile::storage::cephmds::manage_firewall:  true

profile::base::common::packages:
  'redhat-lsb-core': {}
  'bash-completion': {}
  'bash-completion-extras': {}
  'jq': {}
