---
include:
  default:
    - profile::openstack::compute::consoleproxy

profile::openstack::compute::consoleproxy::spice: true

nova::config::nova_config:
    DEFAULT/ssl_only:
      value: true
    DEFAULT/cert:
      value: "/etc/pki/tls/certs/%{hiera('console_ssl_files')}.crt"
    DEFAULT/key:
      value: "/etc/pki/tls/private/%{hiera('console_ssl_files')}.key"
