---
include:
  default:
    - profile::openstack::image
    - profile::logging::rsyslog::client

profile::openstack::image::registry_enabled:  true

accounts::users:
  'cinder':
    ensure: present

accounts::usergroups:
  'cinder':
    - 'cinder'

accounts::accounts:
  'cinder':
    ensure: present

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  rdo-release:
    ensure: present
  ceph:
    ensure: present
