---
include:
  default:
    - profile::logging::rsyslog::server
    - profile::logging::logstash
    - profile::logging::elasticsearch
    - profile::logging::kibana

rsyslog::perm_dir:    '0755'

profile::logging::elasticsearch::instances:
  'openstack':
    datadir:  '/opt/els/openstack'
    config:
      'cluster.name':             "logger"
      'index.number_of_replicas': '0'
      'index.number_of_shards':   '1'
      'network.host':             "127.0.0.1"
      'node.name':                "%{::hostname}"

profile::base::common::packages:
  - java-1.8.0-openjdk

lvm::volume_groups:
  vg_log:
    physical_volumes:
      - /dev/vdb
    logical_volumes:
      lv_log:
        fs_type:   xfs
        mountpath: "/opt"
