---
include:
  default:
    - profile::base::login
    - profile::network::services
    - profile::application::git
    - profile::bootstrap::himlar

profile::base::firewall::manage_firewall: false
profile::network::services::manage_nat: true

profile::firewall::pre::ssh_settings:
  source: "0.0.0.0/0"

accounts::accounts:
  'hege':
    ensure: present
    authorized_keys: [ 'hege_usit', 'hege_home' ]
  'kolbu':
    ensure: present
  'mikaeld':
    ensure: present
  'raymond':
    ensure: present
  'torldre':
    ensure: present
  'trondham':
    ensure: present
  'jarleb':
    ensure: present
  # disable system users
  'iaas':
    ensure: absent
  'vagrant':
    ensure: absent

#openstack_extras::repo::redhat::redhat::manage_rdo: true
profile::base::common::packages:
  'python-oslo-log': {}
  'python-openstackclient': {}

ssh::server::options:
  # Need this for 2FA (saz-ssh-module disables by default)
  ChallengeResponseAuthentication: 'yes'
  # The second publickey is until the pam files are fixed
  AuthenticationMethods: 'publickey,keyboard-interactive:pam'
  # Explicitly enable the required methods
  UsePAM: 'yes'
  PasswordAuthentication: 'no'
  PubKeyAuthentication: 'yes'
  # No 2FA possible with gitolite
  'Match User git':
    AuthenticationMethods: 'publickey'

googleauthenticator::pam::mode::modes:
  wheel-only:
    condition: 'user ingroup wheel'
    nullok: false

googleauthenticator::pam::modules:
  sshd:
    mode: wheel-only

profile::application::git::settings:
  hostname:     "git.%{::domain}"
  upstream:     'enable'
  mirroring:    'enable'
  site_info:    'Please see http://iaas.readthedocs.org for more info'
