---
include:
  default:
    - profile::messaging::rabbitmq
    - profile::openstack::compute::api
    - profile::openstack::compute::scheduler
    - profile::openstack::compute::conductor
    - profile::openstack::compute::consoleauth
    - profile::openstack::compute::consoleproxy
    - profile::openstack::identity
    - profile::openstack::image::api
    - profile::openstack::image::registry
    - profile::openstack::volume
    - profile::openstack::volume::api
    - profile::openstack::volume::scheduler
    - profile::openstack::volume::storage
    - profile::openstack::network::controller
    - profile::openstack::resource::createnetworks
#    - profile::openstack::network::dhcp
#    - profile::openstack::network::l3
#    - profile::openstack::network::metadata
    - profile::application::etcd
    - profile::openstack::resource::dataporten
    - profile::openstack::adminrc
    - profile::application::himlarcli
    - profile::logging::rsyslog::client

profile::openstack::adminrc::auth_url:    "%{hiera('endpoint_protocol')}://%{hiera('service__address__keystone_public')}:5000/v3"
profile::openstack::adminrc::password:    "%{hiera('keystone_admin_password')}"
profile::openstack::adminrc::region_name: "%{::location}"
profile::openstack::adminrc::username:    'admin'
profile::openstack::adminrc::tenant_name: 'openstack'

profile::base::network::node_multinic: true
profile::base::common::manage_lvm: false
profile::base::common::packages:
  'python-etcd': {}

profile::openstack::identity::keystone_config:
  DEFAULT/secure_proxy_ssl_header:
    value:  'HTTP_X_FORWARDED_PROTO'

profile::openstack::identity::roles_extra:
  - user

profile::openstack::resource::dataporten::manage_dataporten: true
profile::openstack::resource::dataporten::domain:
  dataporten:
    ensure:       present
    description:  'Federated users from Dataporten'
    is_default:   false

calico::controller: true

openstack_extras::repo::redhat::redhat::manage_rdo: false

lvm::logical_volume:
  lv_var:
    volume_group: vg_root
    fs_type: xfs
    mountpath: /var/lib/ekstradisk

sudo::purge: false

etcd::mode: cluster
etcd::node_name: 'master'

profile::openstack::network::policies:
  create_network:
    key:   'create_network'
    value: 'rule:admin_only'
  create_router:
    key:   'create_router'
    value: 'rule:admin_only'

profile::openstack::volume::type:
  rbd:
    set_key: 'volume_backend_name'
    set_value: 'rbd-volumes'
    os_tenant_name: 'services'
    os_password: "%{hiera('cinder_api_password')}"
    os_username: 'cinder'
    os_region_name: "%{location}"
    os_auth_url: "http://%{hiera('service__address__keystone')}:5000/v2.0"

profile::openstack::volume::backend::rbd:
  rbd-volumes:
    rbd_pool: 'volumes'
    rbd_user: 'cinder'
    rbd_secret_uuid: "%{hiera('client.cinder::secret')}"

cinder::backends::enabled_backends:
  - rbd-volumes
