---
# Remove old stuff from mgmt role
profile::base::network::cumulus_ifs:              false
network::config_file_per_interface:               false

profile::base::common::manage_chrony:  false

openstack_extras::repo::debian::debian::package_require: false

profile::network::leaf::manage_license: false

openstack_extras::repo::debian::debian::manage_deb:  false
openstack_extras::repo::debian::debian::source_hash:
  buster:
    ensure: absent

# Network config
network::interfaces_type: 'config_db::main'
network::use_config_class: true
network::config_db::main::config_db_file: '/etc/sonic/config_db.json.pending'
