---
include:
  default:
    - profile::openstack::network::controller
    - profile::openstack::resource::createnetworks
    - profile::application::etcd
    - profile::logging::rsyslog::client

profile::base::common::packages:
  'python-etcd': {}
  'python-openstackclient': {}

etcd::mode: cluster
etcd::node_name: 'master'

calico::controller: true

profile::openstack::network::policies:
  create_network:
    key:   'create_network'
    value: 'rule:admin_only'
  create_router:
    key:   'create_router'
    value: 'rule:admin_only'

profile::openstack::network::calico::manage_bird: false

# openstack-neutron-common creates a sudoers.d file that
# maybe should be managed
sudo::purge: false
