---
# This is the authoritative name server
profile::dns::ns::authoritative: true

# Any zones should be placed in the "primary zone" dir
profile::dns::ns::zonedir: 'pz'

# Turn on SELinux
profile::base::selinux::manage_selinux: true

# Turn on the "named_write_master_zones" SELinux boolean
profile::base::selinux::boolean:
  'named_write_master_zones':
    ensure: 'on'
    persistent: true
