---
include:
  default:
    - profile::network::leaf
    - profile::base::common
  bootstrap:
    - profile::base::common

profile::base::common::classes:
  - puppet
  - openstack_extras::repo::debian::debian

profile::base::common::manage_keyboard:           false
profile::base::common::include_virtual:           false
profile::base::common::include_physical:          false
profile::base::common::manage_yumrepo:            false
profile::base::firewall::manage_firewall:         false
profile::base::network::net_ifnames:              false
profile::monitoring::sensu::agent::enable_agent:  false
profile::network::leaf::manage_quagga:            false
profile::network::leaf::manage_frrouting:         true
profile::network::leaf::manage_acls:              true
profile::base::network::cumulus_ifs:              true
network::config_file_per_interface:               true
profile::logging::logrotate::manage_logrotate:    false

# ntp service managed by profile because of mgmt VRF
ntp::service_enable: false
ntp::service_ensure: 'stopped'

frrouting::zebra:                 true
frrouting::bgpd:                  true
frrouting::single_config_file:    true
frrouting::frrouting::hostname:   'cumulus-test'
frrouting::frrouting::password:   'pass123'
frrouting::frrouting::bgp_as:     "%{hiera('bgp_as')}"

profile::network::leaf::acls:
  '02control_plane_custom.rules':
    rule_vars:
      - "INGRESS_CHAIN = INPUT"
      - "INGRESS_INTF = swp+"
    iptables:
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_mgmt_netpart')}.0/%{hiera('netcfg_mgmt_netmask')} -p tcp --dport 19999 -j ACCEPT"
      - "-A $INGRESS_CHAIN -p tcp --dport 19999 -j DROP"
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_trp_netpart')}.0/%{hiera('netcfg_trp_netmask')} -p tcp --dport 179 -j ACCEPT"
      - "-A $INGRESS_CHAIN -p tcp --dport 179 -j DROP"
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_mgmt_netpart')}.0/%{hiera('netcfg_mgmt_netmask')} -p tcp --dport 22 -j ACCEPT"
      - "-A $INGRESS_CHAIN -s %{hiera('netcfg_trp_netpart')}.0/%{hiera('netcfg_trp_netmask')} -p tcp --dport 22 -j ACCEPT"
      - "-A $INGRESS_CHAIN -p tcp --dport 22 -j DROP"
    ip6tables:
      - "-A $INGRESS_CHAIN --in-interface $INGRESS_INTF -s %{hiera('netcfg_trp_netpart6')}::/%{hiera('netcfg_trp_netmask6')} -p tcp -m multiport --dports 22,179 -j ACCEPT"
      - "-A $INGRESS_CHAIN --in-interface $INGRESS_INTF -p tcp  -m multiport --dports 22,179 -j DROP"

accounts::groups:
  'wheel':
    ensure: 'present'

openstack_extras::repo::debian::debian::package_require: true
openstack_extras::repo::debian::debian::manage_uca: false
openstack_extras::repo::debian::debian::manage_whz: false
openstack_extras::repo::debian::debian::source_hash:
  'jessie':
    'location': 'http://ftp.no.debian.org/debian'
    'repos':    'main'

profile::base::common::packages:
  'vim-enhanced': { 'ensure': 'absent', }
  'bind-utils': { 'ensure': 'absent', }
  'yum-utils': { 'ensure': 'absent', }
  'augeas-tools': {}

sudo::configs:
  snmp:
    content:
      - '# SNMP needs access to the bcmcmd to serve up some of the MIBs.'
      - 'snmp ALL = NOPASSWD: /usr/lib/cumulus/bcmcmd'
      - 'snmp ALL = NOPASSWD: /usr/cumulus/bin/cl-resource-query'
      - 'snmp ALL=(root) NOPASSWD: /sbin/ethtool -S *'
      - 'snmp ALL=(root) NOPASSWD: /sbin/ip'

profile::base::network::cumulus_interfaces:
  'lo':
    'addr_method': 'loopback'

frrouting::frrouting::zebra_interfaces:
  'bridge':
    - 'link-detect'
    - 'description linux-bridge'
  'bridge.100':
    - 'link-detect'
    - 'description linux-bridge-100'
  'bridge.109':
    - 'link-detect'
    - 'description linux-bridge-109'
  'host1':
    - 'link-detect'
  'host2':
    - 'link-detect'
  'host3':
    - 'link-detect'
  'host4':
    - 'link-detect'
  'host5':
    - 'link-detect'
  'host6':
    - 'link-detect'
  'host7':
    - 'link-detect'
  'host8':
    - 'link-detect'
  'host9':
    - 'link-detect'
  'host10':
    - 'link-detect'
  'host11':
    - 'link-detect'
  'host12':
    - 'link-detect'
  'host13':
    - 'link-detect'
  'host14':
    - 'link-detect'
  'host15':
    - 'link-detect'
  'host16':
    - 'link-detect'
  'host17':
    - 'link-detect'
  'host18':
    - 'link-detect'
  'host19':
    - 'link-detect'
  'host20':
    - 'link-detect'
  'host21':
    - 'link-detect'
  'host22':
    - 'link-detect'
  'host23':
    - 'link-detect'
  'host25':
    - 'link-detect'
  'host26':
    - 'link-detect'
  'host27':
    - 'link-detect'
  'host28':
    - 'link-detect'
  'host29':
    - 'link-detect'
  'host30':
    - 'link-detect'
  'host31':
    - 'link-detect'
  'host32':
    - 'link-detect'
  'host33':
    - 'link-detect'
  'host34':
    - 'link-detect'
  'host35':
    - 'link-detect'
  'host36':
    - 'link-detect'
  'host37':
    - 'link-detect'
  'host38':
    - 'link-detect'
  'host39':
    - 'link-detect'
  'host40':
    - 'link-detect'
  'host41':
    - 'link-detect'
  'host42':
    - 'link-detect'
  'host43':
    - 'link-detect'
  'host44':
    - 'link-detect'
  'host45':
    - 'link-detect'
  'host46':
    - 'link-detect'
  'host49':
    - 'link-detect'
  'host50':
    - 'link-detect'
  'host51':
    - 'link-detect'
  'host52':
    - 'link-detect'
  'host53':
    - 'link-detect'
  'host57':
    - 'link-detect'
  'host58':
    - 'link-detect'
  'swp47':
    - 'link-detect'

frrouting::frrouting::zebra_generic_options:
  'ip':
    'forwarding'
  'ipv6':
    'forwarding'

frrouting::frrouting::bgp_as: "%{hiera('bgp_as')}"

frrouting::frrouting::bgp_options:
  - "bgp router-id %{hiera('netcfg_trp_netpart')}.1"
  - 'bgp log-neighbor-changes'
  - 'bgp default local-preference 200'
  - 'maximum-paths ibgp 5'
  - 'bgp bestpath as-path multipath-relax'

frrouting::frrouting::bgp_networks:
  - '0.0.0.0/0'
  - '172.18.0.0/21'
  - '109.105.125.0/26'
frrouting::frrouting::bgp_networks6:
  - '::/0'
  - 'fd00::/64'

frrouting::frrouting::bgp_neighbor_groups:
  'rr-clients':
    'options':
      - 'peer-group'
      - "remote-as %{hiera('bgp_as')}"
      - 'route-reflector-client'
      - 'soft-reconfiguration inbound'
      - 'route-map rr-client-allow in'
      - 'bfd'
    'members':
#      - '172.18.0.17'
#      - '172.18.0.18'
#      - '172.18.0.26'
#      - '172.18.0.27'
#      - '172.18.0.103'
#      - '172.18.0.104'
#      - '172.18.0.105'
#      - '172.18.0.111'
#      - '172.18.0.112'
#      - '172.18.0.113'
#      - '172.18.0.115'
#      - '172.18.0.116'
#      - '172.18.0.117'
#      - '172.18.0.118'
#      - '172.18.1.11'
#      - '172.18.1.12'
#      - '172.18.1.13'
#      - '172.18.1.14'
#      - '172.18.1.15'
#      - '172.18.1.16'
#      - '172.18.1.17'
#      - '172.18.1.18'
#      - '172.18.1.19'
#      - '172.18.1.20'
#      - '172.18.1.21'
#      - '172.18.1.22'
#      - '172.18.1.23'
#      - '172.18.1.24'
#      - '172.18.1.25'
#      - '172.18.1.26'
#      - '172.18.1.27'
#      - '172.18.1.28'
#      - '172.18.1.29'
#      - '172.18.1.30'
#      - '172.18.1.31'
#      - '172.18.1.32'
#      - '172.18.1.33'
#      - '172.18.1.34'
      - '172.18.1.49'
    'options6':
      - 'neighbor rr-clients route-reflector-client'
      - 'maximum-paths ibgp 5'
    'members6':
#      - 'fd00::17'
#      - 'fd00::18'
#      - 'fd00::103'
#      - 'fd00::104'
#      - 'fd00::105'
#      - 'fd00::111'
#      - 'fd00::112'
#      - 'fd00::113'
#      - 'fd00::115'
#      - 'fd00::116'
#      - 'fd00::117'
#      - 'fd00::118'
#      - 'fd00::1:11'
#      - 'fd00::1:12'
#      - 'fd00::1:13'
#      - 'fd00::1:14'
#      - 'fd00::1:15'
#      - 'fd00::1:16'
#      - 'fd00::1:17'
#      - 'fd00::1:18'
#      - 'fd00::1:19'
#      - 'fd00::1:20'
#      - 'fd00::1:21'
#      - 'fd00::1:22'
#      - 'fd00::1:23'
#      - 'fd00::1:24'
#      - 'fd00::1:25'
#      - 'fd00::1:26'
#      - 'fd00::1:27'
#      - 'fd00::1:28'
#      - 'fd00::1:29'
#      - 'fd00::1:30'
#      - 'fd00::1:31'
#      - 'fd00::1:32'
#      - 'fd00::1:33'
#      - 'fd00::1:34'
      - 'fd00::1:49'
#  'other-clients':
#    'options':
#    - 'peer-group'

frrouting::frrouting::bgp_accesslist:
  '10':
    - 'permit 158.39.74.0 0.0.0.255'
    - 'permit 158.39.77.0 0.0.0.255'
    - 'permit 10.1.0.0 0.0.15.255'
    - 'permit 172.18.0.0 0.0.7.255'
  '20':
    - 'deny 158.39.74.0 0.0.0.255'
    - 'deny 158.39.77.0 0.0.0.255'
    - 'deny 10.1.0.0 0.0.15.255'
    - 'deny 172.18.0.0 0.0.7.255'
    - 'permit any'

frrouting::frrouting::bgp_ip_prefix_list:
  - 'routes-from-leaf1 seq 5 deny any'
  - 'routes-to-leaf1 seq 5 permit 0.0.0.0/0'

frrouting::frrouting::bgp_route_maps:
  'rr-client-allow permit 10':
    - 'match ip address 10'
  'peer-deny deny 10':
    - 'match ip address 10'
