---
# include default for vagrant to avoid having to reinstall to test the proxy module
#include:
#  default:
#    -  profile::network::yum_proxy
#
# include this to get automatic patching after installation
include:
  default:
    - profile::development::patch
    - profile::monitoring::collectd

# The current vagrant box image do not have vda3 parso switch
# off lvm for compute on vagrant
profile::base::common::manage_lvm: false

# The next two for testing proxy.sh creation, normally not needed in vagrant environments
#profile::base::network::manage_httpproxy: 'true'
#profile::base::network::http_proxy:       'updateproxy.uio.no:3128'
#profile::base::network::http_proxy:       'www-cache.uib.no:81'

# to configure yum proxy set this appropriately
profile::network::yum_proxy::yum_proxy: ''
#profile::network::yum_proxy::yum_proxy: 'http://updateproxy.uio.no:3128'
#profile::network::yum_proxy::yum_proxy: 'http://www-cache.uib.no:81'

profile::base::lvm::physical_volume:
  '/dev/vda3':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/vda3

# test telemetry polling (require metric and telemetry nodes in vagrant)
#profile::openstack::compute::manage_telemetry: true

# enable consul
#include:
#  default:
#    - profile::application::consul

consul::services:
  'foreman':
    tags: ["TheForeman"]
    port: 80

# Add custom routing table for private network to NAT
profile::base::network::routes:
  'eth2':
    'ipaddress': [ '0.0.0.0', '0.0.0.0', ]
    'netmask':   [ '0.0.0.0', '0.0.0.0', ]
    'gateway':   [ "%{hiera('netcfg_priv_gateway')}", "%{hiera('netcfg_trp_gateway')}" ]
    'table':     [ 'private', 'main', ]
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
profile::base::network::rules:
  'eth2':
    iprule: [ "from %{hiera('netcfg_priv_network')} lookup private", ]

profile::monitoring::sensu::agent::checks:
  'nova-ssh-key':
    ensure:       absent

# Red Hat Subscription Management (RHSM)
profile::rhsm::subscription::manage: false
profile::rhsm::virtwho::manage:      false

# collectd
profile::monitoring::collectd::enable: false
profile::monitoring::collectd::plugins:
  - collectd::plugin::aggregation
  - collectd::plugin::cpu
  - collectd::plugin::disk
  - collectd::plugin::load
  - collectd::plugin::memory
  - collectd::plugin::interface
  - collectd::plugin::write_graphite
  - collectd::plugin::virt
  - collectd::plugin::numa
  - collectd::plugin::processes

# FIXME:sensu-go
profile::base::common::packages:
  'gcc-c++': { ensure: absent }
  'make': { ensure: absent }
  'python3-redis': {} # OSProfiler dependency

profile::openstack::compute::manage_osprofiler: true

profile::storage::cephclient::enable: false

profile::monitoring::sensu::agent::checks:
  check-metadata-api:
    command:                'http-check --url http://127.0.0.1:8775'
    interval:               60
    subscriptions:          ['entity:%{::hostname}']
    handlers:               ['default']
    runtime_assets:
    - sensu/http-check
  check-etcd-client-health:
    command:                'http-check --url http://127.0.0.1:2379/health -s true'
    interval:               60
    subscriptions:          ['entity:%{::hostname}']
    handlers:               ['default']
    runtime_assets:
    - sensu/http-check
  'redfish-check':
    command:                '/usr/local/bin/redfish_check.sh'
    interval:               1800
    subscriptions:          ['entity:%{::hostname}']
    handlers:               ['default']
  'dhcp-agent-check':
    command:                '/usr/local/bin/calico_dhcp_agent_check.sh'
    interval:               600
    subscriptions:          ['entity:%{::hostname}']
    handlers:               ['default']
