---
# enable consul
#include:
#  default:
#    - profile::application::consul

profile::base::common::manage_lvm: false

himlar_bootstrap::virt_install:
  '%{location}-admin-01':
    domain:          '%{domain}'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      "%{hiera('netcfg_mgmt_netpart')}.11"
    install_netmask: "%{hiera('netcfg_mgmt_netmask')}"
    install_gateway: "%{hiera('netcfg_mgmt_gateway')}"
    vm_vcpus:        1
    vm_memory:       1024
    vm_console:      false
