---
include:
  bootstrap:
    - profile::application::openssl

named_interfaces::config:
  mgmt:
    - eth1
  core:
    - eth1
  uib:
    - eth2

sensu_etcd_cluster: "backend1=http://%{hiera('netcfg_mgmt_netpart')}.14:2380,backend2=http://%{hiera('netcfg_mgmt_netpart')}.15:2380"

profile::application::openssl::manage_ca_cert:  true
profile::application::openssl::certs:
  "%{::fqdn}":
    cn:     "%{::fqdn}"
    altnames:
      - "%{::fqdn}"
      - "%{hiera('mgmt__address__monitor')}"

profile::monitoring::sensu::agent::enable_agent:      false
