---
profile::network::services::manage_dhcp: true

accounts::accounts:
  'vagrant':
    ensure: present
  'iaas':
    ensure: absent

profile::application::git::settings:
  hostname: "login%{::hostid}"

ssh::server::options:
  'Match User vagrant':
     AuthenticationMethods: 'publickey'
