---

# In the vagrant environment the master role include the console(proxy) functionality
# to conserve resources

include:
  default:
    - profile::network::localdns
    - profile::logging::rsyslog::client
    - profile::openstack::compute::consoleproxy
    - profile::application::sslcert


calico::compute_manage_bird_config:   false
calico::reflector::bird_template:     'calico/compute/bird.conf.erb'
calico::reflector::bird6_template:    'calico/compute/bird6.conf.erb'
calico::reflector: true

profile::openstack::network::controller::neutron_nova_insecure: true

profile::openstack::adminrc::cacert:  '/opt/himlar/provision/ca/certs/ca-chain.cert.pem'

profile::openstack::resource::networks:
  public:
    name: 'public'
    admin_state_up: true
    shared: true
    tenant_name: 'openstack'
    provider_network_type: 'local'

profile::openstack::resource::subnets:
  public:
    name: 'public'
    cidr: '172.31.24.0/24'
    ip_version: '4'
    allocation_pools:
      - 'start=172.31.24.200,end=172.31.24.250'
    gateway_ip: '172.31.24.1'
    dns_nameservers:
      - '129.177.6.54'
      - '129.177.12.31'
    network_name: 'public'
    tenant_name: 'openstack'


# consoleproxy data (normally in 'console.yaml')

profile::openstack::compute::consoleproxy::spice: true
console_ssl_files:  "vagrant-master-01.himlar.local"

nova::config::nova_config:
    DEFAULT/cert:
      value: "/etc/pki/tls/certs/%{hiera('console_ssl_files')}.crt"
    DEFAULT/key:
      value: "/etc/pki/tls/private/%{hiera('console_ssl_files')}.key"

