---
include:
  default:
    - profile::dns::ns
    - profile::dns::rndc_key
    - profile::logging::rsyslog::client

profile::dns::rndc_key::host_is_bind_server:      true

# DNS server addresses (used by file templates)
#profile::dns::ns::mdns_transport_addr: "%{hiera('service__address__mdns')}"
profile::dns::ns::admin_mgmt_addr:          "%{hiera('netcfg_mgmt_netpart')}.11"
profile::dns::ns::ns_mgmt_addr:             "%{hiera('netcfg_mgmt_netpart')}.16"
profile::dns::ns::resolver1_mgmt_addr:      "%{hiera('netcfg_mgmt_netpart')}.17"
profile::dns::ns::resolver2_mgmt_addr:      "%{hiera('netcfg_mgmt_netpart')}.18"
profile::dns::ns::ns_transport_addr:        "%{hiera('service__address__ns')}"
profile::dns::ns::resolver1_transport_addr: "%{hiera('service__address__resolver_01')}"
profile::dns::ns::resolver2_transport_addr: "%{hiera('service__address__resolver_02')}"
profile::dns::ns::ns_public_addr:           "%{hiera('public__address__ns')}"
profile::dns::ns::ns_public6_addr:          "%{hiera('public6__address__ns')}"
profile::dns::ns::resolver1_public_addr:    "%{hiera('public__address__resolver_01')}"
profile::dns::ns::resolver1_public6_addr:   "%{hiera('public6__address__resolver_01')}"

# DNS server firewall configuration
profile::dns::ns::manage_firewall: true
profile::dns::ns::firewall_extras:
  source: "%{::network_trp1}/%{::netmask_trp1}"

# Our internal zone
profile::dns::ns::internal_zone: "vagrant.iaas.intern"

# Forward zones. Only zones that are "internal". Requests for records
# in these zones will be forwarded to the authoritative DNS server
profile::dns::ns::fw_zones:
  internal:
    zone: "%{hiera('profile::dns::ns::internal_zone')}"
    filename: "%{hiera('profile::dns::ns::zonedir')}/%{hiera('profile::dns::ns::internal_zone')}"

# Reverse zones. Only zones that are "internal". Requests for records
# in these zones will be forwarded to the authoritative DNS server
profile::dns::ns::ptr_zones:
  internal:
    cidr: "172.31.0.0/16"
    origin: "31.172.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/31.172.in-addr.arpa"
  public:
    cidr: "192.168.0/16"
    origin: "168.192.in-addr.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/168.192.in-addr.arpa"
  ipv6:
    cidr: "fc00::/7"
    origin: "c.f.ip6.arpa"
    filename: "%{hiera('profile::dns::ns::zonedir')}/c.f.ip6.arpa"
