---
profile::storage::cephfs::create_cephfs: true
profile::storage::cephfs::filesystems:
  'cephfs_internal':
    metadata_pool:     "cephfs_internal_meta"
    primary_data_pool: "cephfs_internal_data_default"
