---
profile::base::selinux::manage_selinux:         false

# FIXME:sensu-go
profile::monitoring::sensu::agent::checks:              {}

# FIXME:ceph-metric
include:
  default:
    - profile::monitoring::telegraf

profile::monitoring::telegraf::enable_telegraf:     true
profile::monitoring::telegraf::outputs:
  influxdb_v2:
    options:
      - urls: ["https://%{hiera('mgmt__address__influx')}:8086"]
        tls_ca: '/etc/puppetlabs/puppet/ssl/certs/ca.pem'
        token: "%{hiera('influxdb_admin_token')}"
        organization: "%{hiera('profile::monitoring::influxdb::org')}"
        bucket: 'ceph'
profile::monitoring::telegraf::inputs: {}

profile::base::yumrepo::repo_hash:
  influxdb:
    ensure: present
