---
named_interfaces::config:
  mgmt:
     - bond0
  trp:
     - bond0.912
  transport: #FIXME
     - bond0.912
  service: #FIXME
     - bond0_912

ntp::servers:
  - 172.28.0.100
  - 172.28.0.101
  - 172.28.0.102

profile::base::network::routes:
  "%{::interface_trp1}":
    'ipaddress': [ '0.0.0.0', ]
    'netmask':   [ '0.0.0.0', ]
    'gateway':   [ "%{hiera('netcfg_priv_gateway')}", ]
    'table':     [ 'private', ]
profile::base::network::routing_tables:
  'private':
    'table_id':  '240'
profile::base::network::rules:
  "%{::interface_trp1}":
    iprule: [ "from %{hiera('netcfg_priv_network')} lookup private", ]
