---
named_interfaces::config:
  mgmt:
     - bond0
  trp:
     - bond0_912
  transport: #FIXME
     - bond0_912
  service: #FIXME
     - bond0_912

ntp::servers:
  - 172.28.0.100
  - 172.28.0.101
  - 172.28.0.102
