---
himlar_bootstrap::virt_install:
  '%{location}-admin-01':
    domain:          '%{domain}'
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      '172.28.0.11'
    install_netmask: '255.255.255.0'
    install_gateway: '172.28.0.10'
    vm_console:      false
