---
named_interfaces::config:
  mgmt:
    - em3
  transport:
    - team1
  trp:
    - team1
  ceph:
    - team1.110

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }
  ceph:
    'defroute': 'no'

profile::base::network::network_auto_bonding:
  trp:
    p3p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p3p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

# Disable intel c states for performance
profile::base::physical::disable_intel_cstates: true

#profile::base::common::extraswap:         true
#profile::base::common::extraswap_sizegb:  20
#profile::base::common::extraswap_fileloc: '/var/lib/swap/swapfile'
# Ensure that the BOSS device is the last device
profile::base::physical::load_ahci_last: true
profile::base::physical::load_ahci_last_scsidrv: 'mpt2sas'

profile::base::selinux::manage_selinux: false

#profile::base::common::manage_fake_ssd: true

# FIXME
profile::base::common::manage_lvm:                  false
profile::base::lvm::create_lvm:                     false
profile::storage::cephosd::create_osds:             false
profile::storage::cephosd::crush_move:              false
profile::storage::cephpool::manage_ec_pools:        false
profile::storage::cephpool::manage_cephpool_params: false

#profile::base::lvm::physical_volume:
#  '/dev/sda3':
#    ensure: present
#    force:  true
#profile::base::lvm::volume_group:
#  'vg_journala':
#    physical_volumes:
#      - /dev/sda3
#profile::base::lvm::logical_volume:
#  lv_journala01:
#    size:         11G
#    volume_group: 'vg_journala'
#    fs_type:      xfs
#    mountpath:    "/journal/journala01"

profile::storage::cephosd::osds:
  '/dev/sdb': {}
  '/dev/sdc': {}
#    db_device: '/dev/sdm'
#    wal_device: '/dev/sdm'
  '/dev/sdd': {}
  '/dev/sde': {}
  '/dev/sdf': {}
  '/dev/sdg': {}
  '/dev/sdh': {}
  '/dev/sdi': {}
  '/dev/sdj': {}
  '/dev/sdk': {}
  '/dev/sdl': {}
#  '/dev/sdm':
#    journal: '/journal/journala11/journal'
#  '/dev/sdn':
#    journal: '/journal/journala12/journal'
#  '/dev/sdo':
#    journal: '/journal/journala13/journal'
#  '/dev/sdp':
#    journal: '/journal/journala14/journal'
#  '/dev/sdq':
#    journal: '/journal/journala15/journal'

profile::storage::ceph::pool::pools:
  'rbd':
    ensure: absent
  'volumes':
    size:    3
    pg_num:  2048
    pgp_num: 2048
    tag:     'rbd'
    custom:
      crush_rule: 'hdd-storage'
      nodelete:   'true'
      min_size:   '2'
  'images':
    size:    3
    pg_num:  512
    pgp_num: 512
    tag:    'rbd'
    custom:
      crush_rule: 'hdd-storage'
      nodelete:   'true'
      min_size:   '2'
  'vms':
    size:    3
    pg_num:  256
    pgp_num: 256
    tag:     'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
  'volumes_hdd_ec_meta':
    size:    3
    pg_num:  128
    pgp_num: 128
    tag:     'rbd'
    custom:
      crush_rule: 'ssd-storage'
      nodelete:   'true'
      min_size:   '2'
profile::storage::ceph::pool::ec_pools:
  'placeholder':
    manage: false

profile::storage::ceph_ecpool::ec_pools:
  'volumes_hdd_ec_data':
    pg_num:              "256"
    manage:              true
    allow_ec_overwrites: true
    k_data:              "4"
    m_code:              "1"
    crush_root:          "storage"

profile::storage::cephpool_params::pools:
  'volumes_hdd_ec_data':
    application_enable: 'rbd'

# Sensu
sudo::configs:
  sensu_tty:
    priority: 20
    content:  'Defaults:sensu !requiretty'
  sensu:
    priority: 25
    content:  'sensu ALL=(ALL) NOPASSWD: /opt/sensu/embedded/bin/check-smart.rb'

profile::monitoring::sensu::agent::checks:
  # 'check-smart':
  #   command:      "/usr/bin/sudo /opt/sensu/embedded/bin/check-smart.rb"
  #   interval:     3600
  #   subscribers:  ['checks']
  'metrics-netif':
    type:         'metric'
    command:      'metrics-netif.rb --scheme network.%{::hostname}'
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']
  'metrics-disk':
    type:         'metric'
    command:      'metrics-disk.rb --scheme disk.%{::hostname} -I sd[a-z]$'
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']

profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:   '0.4.0'
    provider: 'sensuclassic_gem'
    source:   'http://download.iaas.uio.no/uh-iaas/gem'

profile::monitoring::sensu::agent::plugins:
  sensu-plugins-network-checks:
    type:         package
    pkg_version:  '4.1.1'
