---
include:
  kickstart:
    - profile::monitoring::sensu::agent

named_interfaces::config:
  mgmt:
     - em3
  trp:
     - bond1
  transport:
     - bond1
  service:
     - bond1

ntp::servers:
  - 172.28.32.100
  - 172.28.32.101
  - 172.28.32.102

profile::base::network::manage_httpproxy:         true
profile::network::yum_proxy::yum_proxy:          "http://%{hiera('service__address__proxy')}:8888"
profile::monitoring::sensu::agent::enable_agent:  true

puppet::cron_cmd: "if [ -e /etc/profile.d/proxy.sh ] ; then source /etc/profile.d/proxy.sh ; fi ; \
  /usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"

################ TEMP DATA - SHOULD BE FIXED IN COMMON #########################
profile::openstack::compute::migration:enable_nova_account: true

calico::compute::bird_template: 'profile/bird/bird.conf.erb'

# Enable intance migration via ssh
profile::firewall::pre::ssh_settings:
  source: "0.0.0.0/0"
