---
profile::openstack::resource::networks:
  public:
    name: 'public'
    admin_state_up: true
    shared: true
    tenant_name: 'openstack'
    provider_network_type: 'local'

profile::openstack::resource::subnets:
  public:
    name: 'public'
    cidr: '10.100.200.0/24'
    ip_version: '4'
    allocation_pools:
      - 'start=10.100.200.2,end=10.100.200.245'
    gateway_ip: '10.100.200.1'
    dns_nameservers:
      - '129.240.2.40'
      - '129.240.2.3'
    network_name: 'public'
    tenant_name: 'openstack'
