---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - bond1
  ceph:
    - bond1

profile::storage::fake_ssds:
  'sdb': {}
  'sdc': {}

profile::storage::cephosd::osds:
  '/dev/sdb': {}
  '/dev/sdc': {}
  '/dev/sdd': {}
  '/dev/sde': {}
  '/dev/sdf': {}
  '/dev/sdg': {}

profile::storage::cephpool::pools:
  'rbd':
    ensure: absent
  'volumes':
    ensure: present
    pg_num: 64
    pgp_num: 64
  'images':
    ensure: present
    pg_num: 64
    pgp_num: 64
  'vms':
    ensure: present
    pg_num: 128
    pgp_num: 128
  'volumes_hdd_ec_meta':
    ensure: absent
profile::storage::cephpool_params::pools:
  'volumes':
    replicas_min_size: 3
  'images':
    replicas_min_size: 3
  'vms':
    replicas_min_size: 3
    crush_rule:        "ssd"

check_ceph_argument:    "-i 'too many PGs per OSD.*'"

# Sensu
sudo::configs:
  sensu_tty:
    priority: 20
    content:  'Defaults:sensu !requiretty'
  sensu:
    priority: 25
    content:  'sensu ALL=(ALL) NOPASSWD: /opt/sensu/embedded/bin/check-smart.rb'

profile::monitoring::sensu::agent::checks:
  'check-smart':
    command:      "/usr/bin/sudo /opt/sensu/embedded/bin/check-smart.rb"
    interval:     3600
    subscribers:  ['checks']
  'metrics-netif':
    type:         'metric'
    command:      'metrics-netif.rb --scheme network.%{::hostname}'
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']
  'metrics-disk':
    type:         'metric'
    command:      'metrics-disk.rb --scheme disk.%{::hostname} -I sd[a-z]$'
    interval:     60
    subscribers:  ['metrics']
    handlers:     ['graphite_tcp']

profile::monitoring::sensu::agent::plugin_gems:
  sensu-plugins-himlar:
    ensure:   '0.4.0'
    provider: 'sensuclassic_gem'
    source:   'http://download.iaas.uio.no/uh-iaas/gem'

profile::monitoring::sensu::agent::plugins:
  sensu-plugins-network-checks:
    type:         package
    pkg_version:  '4.1.1'
