---
accounts::ssh_keys:
  'iaas':
    type:    'ssh-ed25519'
    public:  'AAAAC3NzaC1lZDI1NTE5AAAAIJYP2tD0gY0ikjB3NBJkPPj3MUSp9GpwuRfnDGSEKYcN'
  'iam':
    type:    'ssh-ed25519'
    public:  'AAAAC3NzaC1lZDI1NTE5AAAAIJYP2tD0gY0ikjB3NBJkPPj3MUSp9GpwuRfnDGSEKYcN'

accounts::users:
  'iam':
    comment: 'iam_uib_ita'
    groups:  [ 'users', 'wheel' ]

accounts::accounts:
  'iam':
    ensure: present
