---
named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth0
  public:
    - eth1

profile::network::nat::enable_bird:              false
profile::network::nat::manage_bird_firewall:     false
profile::network::nat::outiface:                 "%{::interface_public1}"
