---
profile::webserver::apache::vhosts:
  dpapp:
    vhost_name:           "access.%{hiera('location_domain')}"
    servername:           "access.%{hiera('location_domain')}"
    redirect_dest:        "https://access.%{hiera('location_domain')}/"
  dpapp_ssl:
    vhost_name:           "access.%{hiera('location_domain')}"
    servername:           "access.%{hiera('location_domain')}"
    ssl_ca:               '/etc/pki/tls/certs/cachain.pem'
    ssl_key:              '/etc/pki/tls/private/access.local3.intern.key'
    ssl_cert:             '/etc/pki/tls/certs/access.local3.intern.crt'
