---
include:
  kickstart:
    - profile::monitoring::sensu::agent

profile::base::network::manage_httpproxy:         true
profile::monitoring::sensu::agent::enable_agent:  true

calico::compute::bird_template: 'profile/bird/bird.conf.erb'

named_interfaces::config:
  mgmt:
    - eth0
  transport:
    - eth0_100
  trp:
    - eth0_100
