---
include:
  default:
    - profile::monitoring::netdata

profile::monitoring::netdata::manage_firewall:  true

# Netdata access
profile::database::mariadb::users:
  'netdata@localhost':
    ensure: present

profile::database::mariadb::grants:
  'netdata@localhost/*.*':
    privileges: ['USAGE']
    table:      '*.*'
    user:       'netdata@localhost'

# Enable extra yum repo
profile::base::yumrepo::repo_hash:
  mariadb:
    ensure:     absent
  "mariadb-%{hiera('mariadb_version')}":
    ensure:     present
