---
profile::openstack::resource::networks:
  public:
    name: 'public'
    admin_state_up: true
    shared: true
    tenant_name: 'openstack'
    provider_network_type: 'local'

profile::openstack::resource::subnets:
  public:
    name: 'public'
    cidr: "%{hiera('netcfg_netpart_public')}.0/24"
    ip_version: '4'
    allocation_pools:
      - "start=%{hiera('netcfg_netpart_public')}.20,end=%{hiera('netcfg_netpart_public')}.180"
    gateway_ip: "%{hiera('netcfg_netpart_public')}.1"
    dns_nameservers:
      - '129.177.6.54'
      - '129.177.12.31'
    network_name: 'public'
    tenant_name: 'openstack'
