---
named_interfaces::config:
  mgmt:
    - eth0
  trp:
    - eth1
  ceph:
    - eth1

profile::storage::cephosd::osds:
#  '/dev/vdb': {} # SSD
  '/dev/vdc': {} # SSD
  '/dev/vdd': {} # HDD
  '/dev/vde': {} # HDD
  '/dev/vdf': {} # HDD
  '/dev/vdg': {} # HDD
  '/dev/vdh': {} # HDD

profile::base::common::manage_fake_ssd: true

profile::storage::fake_ssds:
#  'vdb': {}
  'vdc': {}
