---
profile::application::access::package_url: 'http://folk.uib.no/st02221/yum/himlar-dp-prep-1.0-1.el7.x86_64.rpm'

profile::webserver::apache::vhosts:
  dpapp:
    vhost_name:         "accesstest.iaas.uib.no"
    servername:         "accesstest.iaas.uib.no"
  dpapp_ssl:
    vhost_name:         "accesstest.iaas.uib.no"
    servername:         "accesstest.iaas.uib.no"
    ssl_ca:             "/etc/pki/tls/certs/DigiCertCA.crt"
    ssl_cert:           "/etc/pki/tls/certs/accesstest_iaas_uib_no.crt"
    ssl_key:            "/etc/pki/tls/private/accesstest_iaas_uib_no.key"
