---
include:
  bootstrap:
    - profile::network::yum_proxy
  kickstart:
    - profile::network::yum_proxy

profile::base::network::manage_dummy: true
profile::base::network::no_of_dummies: 2

named_interfaces::config:
  mgmt:
     - eth0
  transport:
     - eth0_912
     - eth1
  service:
     - eth0_912
