---
include:
  bootstrap:
    - profile::network::yum_proxy

profile::network::yum_proxy::yum_proxy: 'http://172.31.1.12:8888'

named_interfaces::config:
  mgmt:
     - eth0
  transport:
     - eth0_912
     - eth1
  service:
     - eth0_912
