---
profile::storage::ceph_crushbucket::buckets:
  'storage':
    bucket_type:   'pod'
    bucket_parent: 'default'
  'dcache':
    bucket_type:   'pod'
    bucket_parent: 'default'

profile::storage::cephmon::create_extraconf: true
profile::storage::ceph_extraconf::config:
  osd_deep_scrub_interval:
    'config_key'  : "mgr/osd_deep_scrub_interval"
    'config_value': "2419200.000000"

profile::base::common::manage_lvm: true
profile::base::lvm::physical_volume:
  '/dev/vdb':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ceph':
    physical_volumes:
      - /dev/vdb
profile::base::lvm::logical_volume:
  'lv_ceph':
    volume_group: 'vg_ceph'
    fs_type:      "xfs"
    mountpath:    "/var/lib/ceph"
