---
# Nover overrides
nova::compute::libvirt::libvirt_cpu_model: 'EPYC'
nova::cpu_allocation_ratio:                '1'

profile::base::physical::enable_redfish_sensu_check: false

profile::base::lvm::physical_volume:
  '/dev/sda3':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_ext':
    physical_volumes:
      - /dev/sda3
profile::base::lvm::logical_volume:
  'lv_instances':
    volume_group: 'vg_ext'
    fs_type:      "xfs"
    mountpath:    "/var/lib/nova/instances"

profile::base::network::network_auto_bonding:
  trp:
    p2p1:
      'team_port_config': '{ "prio" : 100 }'
    p2p2:
      'team_port_config': '{ "prio" : 100 }'
