---
named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1
  live:
    - team1.120

profile::base::network::network_auto_bonding:
  trp:
    p3p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p3p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

#nova::compute::libvirt::libvirt_cpu_model: 'EPYC'
#nova::compute::vgpu::enabled_vgpu_types:   'nvidia-233'
#yum_base_mirror:    'https://download.iaas.uio.no/uh-iaas/vgpu'

# remove when telemetry/ceilometer is up in all environments and move to common
profile::openstack::compute::manage_telemetry: true

profile::base::physical::blacklist_drv: true
profile::base::physical::blacklist_drv_list:
  'nouveau': {}

nova::compute::libvirt::libvirt_cpu_model: 'Skylake-Server-IBRS'

nova::compute::libvirt::libvirt_hw_machine_type: 'x86_64=q35'
# These compute host uses local storage for instances
nova::compute::rbd::ephemeral_storage: false
nova::config::nova_config:
  libvirt/images_type:
    value: default
  DEFAULT/metadata_workers:
    value: '4'
