---
include:
  kickstart:
    - profile::monitoring::sensu::agent

ntp::servers:
  - 172.16.0.100
  - 172.16.0.101
  - 172.16.0.102

profile::base::network::manage_httpproxy:         true
profile::monitoring::sensu::agent::enable_agent:  true

puppet::cron_cmd: "if [ -e /root/proxy.sh ] ; then source /root/proxy.sh ; fi ; \
  /usr/bin/env puppet agent --config %{puppet::dir}/puppet.conf --onetime --no-daemonize"

################ TEMP DATA - SHOULD BE FIXED IN COMMON #########################
calico::compute::bird_template: 'profile/bird/bird.conf.erb'

named_interfaces::config:
  mgmt:
    - em3
  transport:
    - team1
  service:
    - team1
