---
himlar_bootstrap::virt_install:
  '%{location}-admin-01':
    domain:          "%{hiera('domain_mgmt')}"
    libvirt_pool:    'dirpool'
    libvirt_network: 'directnet'
    install_ip:      "%{hiera('netcfg_mgmt_net_c0')}.11"
    install_netmask: "%{hiera('netcfg_mgmt_netmask')}"
    install_gateway: "%{hiera('netcfg_mgmt_net_c0')}.10" #login
    vm_vcpus:        4
    vm_memory:       16192
    vm_console:      false
    use_dhcp:        false

profile::base::physical::configure_bmc_nic:          true
profile::base::physical::enable_redfish_sensu_check: true
profile::monitoring::sensu::agent::checks:
  'redfish-check':
    command:      '/usr/local/bin/redfish_check.sh'
    interval:     1800
    subscribers:  ['checks']

# Cron tabs for power metric
profile::base::common::manage_cron: true
profile::base::cron::crontabs:
  power_metric:
    hour:     '*'
    minute:   '*/5'
    weekday:  '*'
    command:  "/usr/local/bin/power_metric.sh >/dev/null"
