---
profile::base::network::cumulus_bonds:
  'peerlink':
    'slaves': [ 'swp31-32', ]
    'mtu':   '9216'
  'host73':
    'slaves': [ 'swp19s0', ]
    'clag_id': '73'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
    'vids': [ '100', '110', '120', ]
    'mtu': '9216'

# Edgecore as7726 needs explicit config
profile::network::leaf::cumulus_portconfigs:
  19:
    line:  "19=4x25G"
  29:
    line:  "29=100G" # spine 01-02
  30:
    line:  "30=100G" # spine 01-02
  31:
    line:  "31=100G" # peerlink
  32:
    line:  "32=100G" # peerlink

profile::base::network::cumulus_bridges:
  'bridge':
    'ports':
      - host73
      - peerlink
