---
profile::network::services::manage_dhcp:  false

# Himlar bootstrap
profile::bootstrap::himlar::manage_bootstrap_scripts: true
himlar_bootstrap::tftp_install:
  'bgo-controller-01':
    domain:           'mgmt.iaas.intern'
    dhcp_interface:   'eth2'
    dhcp_range_start: '172.16.0.200'
    dhcp_range_end:   '172.16.0.250'
    dhcp_gateway:     '172.16.0.10'
    macaddress:       '01-EC:F4:BB:CC:CE:F4'
  'test01-controller-01':
    domain:           'mgmt.test.iaas.intern'
    dhcp_interface:   'eth0'
    dhcp_range_start: "172.28.0.200"
    dhcp_range_end:   "172.28.0.250"
    dhcp_gateway:     "172.28.0.10"

profile::application::git::settings:
  hostname: "bgo"
