---
profile::openstack::resource::networks:
  public:
    name: 'bgo-public'
    admin_state_up: true
    shared: true
    tenant_name: 'openstack'
    provider_network_type: 'local'

profile::openstack::resource::subnets:
  public:
    name: 'bgo-public'
    cidr: '158.39.77.0/24'
    ip_version: '4'
    allocation_pools:
      - 'start=158.39.77.2,end=158.39.77.245'
    gateway_ip: '158.39.77.1'
    dns_nameservers:
      - '129.177.6.54'
      - '129.177.12.31'
    network_name: 'bgo-public'
    tenant_name: 'openstack'
