---
profile::base::common::manage_cron: true
profile::base::cron::crontabs:
  stats:
    hour:     '*'
    minute:   [14,29,44,59]
    command:  '/opt/himlarcli/bin/gen_stats.sh >/dev/null'
  checks:
    hour:     '*'
    minute:   '*/5'
    command:  '/opt/himlarcli/bin/check_services.sh >/dev/null'
