---
profile::network::leaf::manage_license: true
profile::network::leaf::manage_portconfig: true

# Dellemc S5132f needs explicit config
profile::network::leaf::cumulus_portconfigs:
  1:
    line:  "1=4x25G"
  2:
    line:  "2=4x25G"
  3:
    line:  "3=4x25G"
  4:
    line:  "4=4x25G"
  5:
    line:  "5=4x25G"
  6:
    line:  "6=4x25G"
  7:
    line:  "7=4x25G"
  8:
    line:  "8=4x25G"
  9:
    line:  "9=4x25G"
  10:
    line:  "10=4x25G"
  11:
    line:  "11=4x25G"
  12:
    line:  "12=4x25G"
  13:
    line:  "13=4x25G"
  14:
    line:  "14=4x25G"
  15:
    line:  "15=4x10G" # bgo-storage-08 and 09
  28:
    line:  "28=4x10G" # new uplink uninett
  29:
    line:  "29=40G" # temporary uplink to torack
  30:
    line:  "30=40G" # temporary uplink to torack

profile::base::network::cumulus_interfaces:
  'swp29':
    'speed': '40000'
  'swp30':
    'speed': '40000'

profile::base::network::cumulus_bonds:
  'peerlink':
    'slaves': [ 'swp31-32', ]
  'downlink':
    'slaves': [ 'swp29-30', ]
    'clag_id': '1000'
    'pvid': '100'
    'vids': [ '100', '120', ]
  'host1':
    'slaves': [ 'swp1s0', ]
    'clag_id': '1'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host2':
    'slaves': [ 'swp1s1', ]
    'clag_id': '2'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host3':
    'slaves': [ 'swp1s2', ]
    'clag_id': '3'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host4':
    'slaves': [ 'swp1s3', ]
    'clag_id': '4'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host5':
    'slaves': [ 'swp2s0', ]
    'clag_id': '5'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host6':
    'slaves': [ 'swp2s1', ]
    'clag_id': '6'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host7':
    'slaves': [ 'swp2s2', ]
    'clag_id': '7'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host8':
    'slaves': [ 'swp2s3', ]
    'clag_id': '8'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host9':
    'slaves': [ 'swp3s0', ]
    'clag_id': '9'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host10':
    'slaves': [ 'swp3s1', ]
    'clag_id': '10'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host11':
    'slaves': [ 'swp3s2', ]
    'clag_id': '11'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host12':
    'slaves': [ 'swp3s3', ]
    'clag_id': '12'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host13':
    'slaves': [ 'swp4s0', ]
    'clag_id': '13'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host14':
    'slaves': [ 'swp4s1', ]
    'clag_id': '14'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host15':
    'slaves': [ 'swp4s2', ]
    'clag_id': '15'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host16':
    'slaves': [ 'swp4s3', ]
    'clag_id': '16'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host17':
    'slaves': [ 'swp5s0', ]
    'clag_id': '17'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host18':
    'slaves': [ 'swp5s1', ]
    'clag_id': '18'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host19':
    'slaves': [ 'swp5s2', ]
    'clag_id': '19'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host20':
    'slaves': [ 'swp5s3', ]
    'clag_id': '20'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host21':
    'slaves': [ 'swp6s0', ]
    'clag_id': '21'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host22':
    'slaves': [ 'swp6s1', ]
    'clag_id': '22'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host23':
    'slaves': [ 'swp6s2', ]
    'clag_id': '23'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host25':
    'slaves': [ 'swp7s0', ]
    'clag_id': '25'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host26':
    'slaves': [ 'swp7s1', ]
    'clag_id': '26'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host27':
    'slaves': [ 'swp7s2', ]
    'clag_id': '27'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host28':
    'slaves': [ 'swp7s3', ]
    'clag_id': '28'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host29':
    'slaves': [ 'swp8s0', ]
    'clag_id': '29'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host30':
    'slaves': [ 'swp8s1', ]
    'clag_id': '30'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host31':
    'slaves': [ 'swp8s2', ]
    'clag_id': '31'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host32':
    'slaves': [ 'swp8s3', ]
    'clag_id': '32'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host33':
    'slaves': [ 'swp9s0', ]
    'clag_id': '33'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host34':
    'slaves': [ 'swp9s1', ]
    'clag_id': '34'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host35':
    'slaves': [ 'swp9s2', ]
    'clag_id': '35'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host36':
    'slaves': [ 'swp9s3', ]
    'clag_id': '36'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host37':
    'slaves': [ 'swp10s0', ]
    'clag_id': '37'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host38':
    'slaves': [ 'swp10s1', ]
    'clag_id': '38'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host39':
    'slaves': [ 'swp10s2', ]
    'clag_id': '39'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host40':
    'slaves': [ 'swp10s3', ]
    'clag_id': '40'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host41':
    'slaves': [ 'swp11s0', ]
    'clag_id': '41'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host42':
    'slaves': [ 'swp11s1', ]
    'clag_id': '42'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host43':
    'slaves': [ 'swp11s2', ]
    'clag_id': '43'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host44':
    'slaves': [ 'swp11s3', ]
    'clag_id': '44'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host45':
    'slaves': [ 'swp12s0', ]
    'clag_id': '45'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host46':
    'slaves': [ 'swp12s1', ]
    'clag_id': '46'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host49':
    'slaves': [ 'swp13s0', ]
    'clag_id': '49'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host50':
    'slaves': [ 'swp13s1', ]
    'clag_id': '50'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host51':
    'slaves': [ 'swp13s2', ]
    'clag_id': '51'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host52':
    'slaves': [ 'swp13s3', ]
    'clag_id': '52'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host53':
    'slaves': [ 'swp14s0', ]
    'clag_id': '53'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host57':
    'slaves': [ 'swp15s0', ]
    'clag_id': '57'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true
  'host58':
    'slaves': [ 'swp15s1', ]
    'clag_id': '58'
    'pvid': '100'
    'mstpctl_portadminedge': true
    'mstpctl_bpduguard': true

profile::base::network::cumulus_bridges:
  'bridge':
    'ports':
      - host1
      - host2
      - host3
      - host4
      - host5
      - host6
      - host7
      - host8
      - host9
      - host10
      - host11
      - host12
      - host13
      - host14
      - host15
      - host16
      - host17
      - host18
      - host19
      - host20
      - host21
      - host22
      - host23
      - host25
      - host26
      - host27
      - host28
      - host29
      - host30
      - host31
      - host32
      - host33
      - host34
      - host35
      - host36
      - host37
      - host38
      - host39
      - host40
      - host41
      - host42
      - host43
      - host44
      - host45
      - host46
      - host49
      - host50
      - host51
      - host52
      - host53
      - host57
      - host58
      - peerlink
      - downlink
    'alias_name': 'Transport L2 if'
    'vlan_aware': 'true'
    'stp': 'true'
    'vids': [ '100', '120', '4094', ]
