---
include:
  default:
    - profile::storage::cephclient

#profile::storage::cephclient::create_extraconf: true
#profile::storage::ceph_extraconf::config:
#  client_dcache_backend:
#    'config_key'  : "client.tape/rbd_default_data_pool"
#    'config_value': "dcache_hdd_ec_data"

ceph::profile::params::client_keys:
  'client.tape':
    secret: "%{hiera('ceph_storage_client_tape_key')}"
    mode: '0600'
    user: 'root'
    group: 'root'
    cap_mon: 'profile rbd'
    cap_osd: 'profile rbd pool=dcache_hdd_ec_meta, profile rbd pool=dcache_hdd_ec_data'

profile::base::physical::enable_redfish_sensu_check: false

named_interfaces::config:
  mgmt:
    - em3
  trp:
    - team1

profile::base::network::network_auto_opts:
  trp:
    'defroute': 'no'
    'devicetype': 'Team'
    'mtu': '9000'
    'team_config': >-
                   { "runner" : {  "name" : "lacp",  "active": true, "fast_rate" : true,
                   "tx_hash": ["eth", "ipv4", "ipv6"], "tx_balancer": { "name": "basic" } },
                   "link_watch" : {  "name" : "ethtool" } }

profile::base::network::network_auto_bonding:
  trp:
    p4p1:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'
    p4p2:
      'team_port_config': '{ "prio" : 100 }'
      'mtu': '9000'

profile::base::lvm::physical_volume:
  '/dev/sda':
    ensure: present
    force:  true
  '/dev/sdb':
    ensure: present
    force:  true
  '/dev/sdc':
    ensure: present
    force:  true
  '/dev/sdd':
    ensure: present
    force:  true
  '/dev/sde':
    ensure: present
    force:  true
profile::base::lvm::volume_group:
  'vg_db01':
    physical_volumes:
      - /dev/sda
  'vg_db02':
    physical_volumes:
      - /dev/sdb
  'vg_db03':
    physical_volumes:
      - /dev/sdc
  'vg_logactive':
    physical_volumes:
      - /dev/sdd
  'vg_logarchive':
    physical_volumes:
      - /dev/sde
profile::base::lvm::logical_volume:
  'lv_db01':
    volume_group: 'vg_db01'
    fs_type:      "xfs"
    mountpath:    "/db01"
  'lv_db02':
    volume_group: 'vg_db02'
    fs_type:      "xfs"
    mountpath:    "/db02"
  'lv_db03':
    volume_group: 'vg_db03'
    fs_type:      "xfs"
    mountpath:    "/db03"
  'lv_logactvie':
    volume_group: 'vg_logactive'
    fs_type:      "xfs"
    mountpath:    "/log_active"
  'lv_logarchive':
    volume_group: 'vg_logarchive'
    fs_type:      "xfs"
    mountpath:    "/log_archive"


